name: 构建并发布 Docker 镜像

on:
  workflow_dispatch:
    inputs:
      is_beta:
        type: boolean
        required: true
        description: "开发版"
        default: true
      custom_version:
        type: string
        required: false
        description: "版本号"
        default: ""

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: binbin1213/tiktokdownloader

jobs:
  publish-docker:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取源码
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: 设置 QEMU
        uses: docker/setup-qemu-action@v3

      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 登录到 GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 生成镜像标签
        id: generate-tags
        run: |
          # 确定基础版本
          if [ -n "${{ github.event.inputs.custom_version }}" ]; then
            BASE_VERSION="${{ github.event.inputs.custom_version }}"
          else
            # 获取最新release版本，如果失败则使用默认值
            BASE_VERSION=$(curl -s \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              https://api.github.com/repos/${{ github.repository }}/releases/latest \
              | jq -r '.tag_name // "1.0"')
          fi
          
          # 生成标签
          if [ "${{ inputs.is_beta }}" == "true" ]; then
            # 开发版：简洁的标签
            TAGS="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:dev,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:beta"
          else
            # 正式版
            TAGS="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${BASE_VERSION},${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest"
          fi
          
          echo "Generated tags: $TAGS"
          echo "TAGS=$TAGS" >> $GITHUB_ENV

      - name: 构建和推送 Docker 镜像到 GitHub Container Registry
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ env.TAGS }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
          sbom: false
